server:
  port: 9081 #服务注册中心端口号

spring:
  application:
    name: service-eureka #服务名称--调用的时候根据名称来调用该服务的方法

eureka:
  instance:
    hostname: 127.0.0.1 #服务注册中心IP地址
  client:
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    service-url: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/